name: documentation

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - name: Enable Corepack
        run: corepack enable
      - name: Test Build
        run: |
          yarn install --non-interactive
          yarn build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - name: Enable Corepack
        run: corepack enable
      - name: Release to GitHub Pages
        env:
          GIT_USER: 'x-actor'
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          yarn install --non-interactive
          yarn deploy
